### ISSUE TITLE
Meetup - 12th June 2014

### ISSUE THREAD

**Issue by olizilla** [meteor-london/next#1]
- Meetup details: http://www.meetup.com/Meteor-London/events/184136332/
- Venue: uSwitch, Notcutt House, 36 Southwark Bridge Road, London, SE1 9EU
- [Map](https://www.google.com/maps/preview?f=q&hl=en&q=Notcutt+House,+36+Southwark+Bridge+Road,+London,+gb)

**Comment by olizilla** [comment]
@benfoxall meet @datacarl, @datacarl meet @benfoxall... you're both awesome, and on the line-up for Meteor London tomorrow.

Are you all set? We can pipe HDMI, mini display-port and VGA to the projector, and the wifi is pretty solid. Shout if you have questions, otherwise, we'll be at the venue from 6pm. You're welcome to come a do a tech check before hand. If you're loitering in London and would like to meet earlier, let us know.

**Comment by olizilla** [comment]
aaaand, apologies if you get an email with the wrong date in it. It's late. I should probably stop typing.

**Comment by datacarl** [comment]
Hey guys!

I'll arrive at Gatwick at 4 pm and don't have any plans so I could meet you wherever whenever. Or if you are busy I'll find a café close to uSwitch and hang out there until things are starting.

**Comment by datacarl** [comment]
If you got a charger for the new MacBook pros that would be great. I have
mine but forgot the adapter for British power outlets. I can buy one at the
airport if you don't have one though.

On Wednesday, June 11, 2014, Oli Evans notifications@github.com wrote:

> aaaand, apologies if you get an email with the wrong date in it. It's
> late. I should probably stop typing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meteor-london/next/issues/1#issuecomment-45802916.

## 

Med vänlig hälsning

Carl Littke

+46 (0) 70 272 36 55
Hornsgatan 142
117 28 Stockholm

**Comment by olizilla** [comment]
No worries, I have one. I'm gonna aim to get to uSwitch for 5pm, I'll ping you when I get there.

@benfoxall are you in London town?

**Comment by benfoxall** [comment]
Hello! Looking forward to tonight. Think I'm all set - I gave my talk last night after quite a few beers, think it was a good preparation.

I'm just about in town, though I've got to go for a meeting - I'll head straight over afterward (probably around 5.30-6).

Looking forward to meeting you @datacarl. @olizilla - ace work on the adventure club shout out! It's getting pretty real.

**Comment by benfoxall** [comment]
I really like this github repo for planning.

Really great idea to have potential talks as raised issues. Makes it really easy to flesh out talk descriptions and stuff. Think I'm going to steal that for JS Oxford (no one ever fills out our Google form)

**Comment by olizilla** [comment]
@benfoxall, it's straight up copied from LNUG and the beautiful mind of @andrew... Makes a lot of sense seeing as we are trying to wrangle developers. What time are you heading over to uswitch? It would be good to test out the wifi...

**Comment by andrew** [comment]
@olizilla @benfoxall if you need any private repos for your orgs let me know, we have discount codes for OSS orgs.

**Comment by olizilla** [comment]
@andrew very much yes please for meteor-london.
@datacarl, we're in uSwitch already, so feel free to head over when you're ready.

**Comment by olizilla** [comment]
@datacarl @benfoxall @richsilv @kimon-satan @tomsabin @jongd 
Your videos are up on the Meteor channel: 
https://www.youtube.com/playlist?list=PLTUf4ytkmI8Sb8K3RdMrVNfOl9aCQMrAy
