### ISSUE TITLE
Worldwide Meteor Day - 6 November 2014

### ISSUE THREAD

**Issue by liamwooding** [meteor-london/next#10]
- 6th Nov 2014
- **Mind Candy, Floor 4, 15 Bonhill Street, London EC2A 4DN**

Talks from:
- @ashburnham
- @richsilv
- @Josh-a-e
- @bmordan
- @loopdotcoop

**Comment by chrisckchang** [comment]
@chrischang12 - talk on mongodb

**Comment by ashburnham** [comment]
Looking forward to it.
