### ISSUE TITLE
January 2015 Meetup

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#12]
The time has come to gather once again for the first Meteor London Meetup of 2015. Do you have a talk/demo to share? Get in touch and tell us the title of your talk. Beer and Burritos to your tummy as usual.

---

Join us here:
Makers Academy
Floors 2 and 3
50-52 Commercial Street
London E1 6LT
from 6:30pm

---

Featured Talks:
- 'Peer-to-peer multiplayer in Meteor' (Liam Wooding)
- 'The Internet of Meteor Things' (Michael Karliner)
- 'Meteor at Chaser' (Mark Woodbridge)

Lighting Talks:
- 'Famo.us in your Meteor Project 3 ways' (Bernard Mordan)
- 'Meteor PageSlider' (Richard Silverton)

**Comment by jem-computer** [comment]
No date? Feature or bug?

**Comment by alanshaw** [comment]
When: **Thursday 29th January**
http://www.meetup.com/Meteor-London/events/219957619/

**Comment by cwaring** [comment]
I've announced on the twitters!

**Comment by mrw34** [comment]
I can do a talk titled "Enterprise Meteor"(?) on using Meteor in production for a B2B SaaS

**Comment by alanshaw** [comment]
@mrw34 lightning talk or full fat? May I propose a title change to "USS Enterprise Meteor" :smile:

**Comment by mrw34** [comment]
15-20 minutes or so, if that's ok. Let's just call it "Meteor at Chaser", cos that's what it's about.

**Comment by richsilv** [comment]
Righto, I'll do 5 minutes on Meteor PageSlider.  It really does do what it says on the tin.
