### ISSUE TITLE
March 26th Meetup

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#13]
Thursday 26th March
Makers Academy 2nd Floor 50-52 Commercial Street E1 6LT, London
[meetup](http://www.meetup.com/Meteor-London/events/220779694/)

**Comment by monbro** [comment]
I would like to do a lightning talk about a small meteor side project (using: queue / cronjob system, soundcloud api, private packages, automated twitter / fb sharing, [tsega:filter-collections](https://atmospherejs.com/tsega/filter-collections), using the [mediator pattern](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#mediatorpatternjavascript)).

**Comment by richsilv** [comment]
Jimmy Tidey wants to demo the LocalNets app I'm helping him with at the moment.  Probably just a lightening talk, but we may be able to extend if there is demand.

**Comment by cwaring** [comment]
I'm working on new audio based app that I should have ready to share by the 26th. Maybe we can boot up the satellites and dial in from NYC?

**Comment by alanshaw** [comment]
Hey @monbro are you still up for giving your lightning talk tonight?

**Comment by monbro** [comment]
@alanshaw Yes, I just prepared the presentation.

**Comment by alanshaw** [comment]
:thumbsup:
