### ISSUE TITLE
Guest Stars - 25th June 2015

### ISSUE THREAD

**Issue by alanshaw** [meteor-london/next#15]
http://www.meetup.com/Meteor-London/events/222869111/
# Date

25th June 2015
# Venue

Makers Academy
2nd Floor 50-52 Commercial Street E1 6LT, London
# Speakers
- [Gadi Cohen](https://github.com/gadicc) - Meteor Famous Views
- TBC
# Lightning talks
- TBC
# Special guest

[Alice Yu](https://twitter.com/yaliceme) from MDG.

**Comment by mkarliner** [comment]
Anyone interested in hearing about ThingStudio? ThingStudio is what happened after I gave a talk on IoT and Meteor. We've created a platform for creating shareable apps for talking to IoT devices.

**Comment by chriswessels** [comment]
I'd like to give a lightning talk on running Meteor in production using Docker. Anyone interested?

**Comment by richsilv** [comment]
yes, @chriswessels - that sounds great!

**Comment by michalzacher** [comment]
I can talk about our experience with building a project management platform in Meteor. Details: https://github.com/meteor-london/next/issues/16

**Comment by chriswessels** [comment]
Any update here?

**Comment by olizilla** [comment]
@mkarliner YES! Are you still available?

@chriswessels As @richsilv said, yes! Do you need any more info from us? Are you still interested about talking in Meteor & Docker?

@michalzacher Also yes! but we may need to schedule you in for July, as we may not be able to fit in 4 longer talks. It's first come first served, so if either @mkarliner & @chriswessels can't make it, then you could go this month.

**Comment by mkarliner** [comment]
Yes, I'm available.

**Comment by michalzacher** [comment]
Hey Oli, I tried to reach you through Meetup.com, we spoke about doing a lightning talk also at last meetup. A guy from Poland bought tickets to come to London to talk this Thurstday. We won't be able to come next month, so for us it's now or never in London :) I would really appreciate if you could fit us in...

**Comment by chriswessels** [comment]
@olizilla I am still interested, but alas that evening has been filled with another event. Could we book a lightning talk slot for July?

**Comment by richsilv** [comment]
Okay, that seems to make things fairly straightforward:

@michalzacher - we'd love to have you talk tomorrow evening.

@chriswessels - we'll pencil you in for July and be in touch closer to the time.

Thanks, all!

**Comment by richsilv** [comment]
Apologies, also:

@mkarliner - we would also love to have you talk tomorrow evening.

My brain is not multi-threaded, it would appear.

**Comment by mkarliner** [comment]
15 minutes, right?

Mike

**Comment by richsilv** [comment]
That would be perfect, thanks @mkarliner

**Comment by soulwire** [comment]
Hi there. If possible, myself and @wagerfield would like to take 5-10 minutes tonight to demo a multiplayer game we've created with Meteor. Any chance you can fit us in?

**Comment by bmordan** [comment]
@richsilv I have a lightning talk on static clock 5mins

**Comment by cwaring** [comment]
A big +1 for @soulwire & @wagerfield. @bmordan @olizilla if you can fit these guys in it will be an epic addition to the showcase. Wish I could join you all tonight! :violin:
