### ISSUE TITLE
Show & Tell - Thurs 23rd July

### ISSUE THREAD

**Issue by olizilla** [meteor-london/next#17]
Whose available to help run a meteor london meetup in July?
Venue?
Talks!

**Comment by bmordan** [comment]
We can use Makers Academy.
Rainmakers loft was booked.
Rolling Stock is nice but too small.
We still need a larger venue - that we can stay in until later (11pm)

**Comment by mrw34** [comment]
If you need a spare lightning talk then I can give a demo of using Meteor with [Electron](http://electron.atom.io).

**Comment by olizilla** [comment]
@mrw34 that would be brilliant! Yes please.

**Comment by richsilv** [comment]
Lineup:

@olizilla - Meteor News
@davenyss - Package of the Month

_Lightening Talks:_
@mrw34 - Meteor with Electron
@F4b1n0u - attraction.meteor.com
Hanna Celina - Learning Circle
@bmordan - Static clock!

Please let me know if there's any more or if any of those mentioned above are unable to speak this month.  Thanks!
