### ISSUE TITLE
2015 September 17th - Hackathon Primer

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#20]
Meteor are holding an international 24hr Hackathon on the weekend of Oct 10/11. Our September meetup will focus on preparing the London community to create the awesome. Have you used an API which you think would be a useful tool in a hackathon project? Would you share your experience and knowledge with the community and prepare a 10 min HOW TO:

_for example:_
- how to map
- how to youtube
- how to slingshot
- how to instant message

Add your talk for consideration below

**Comment by vbrajon** [comment]
I can do "how to ionic (mobile app)"

**Comment by olizilla** [comment]
@vbrajon Yes please!

**Comment by ackuser** [comment]
Hi all,
I am really interested in learning Meteor and I want to go to the hackathon. 
However, I am newbie on this subject and I couldn't be in the meetup yesterday.
Is there any available info & material from yesterday such as powerpoint, github repositories or anything else regarding with these for points 
    how to map
    how to youtube
    how to slingshot
    how to instant message

I would appreciate if someone shares what they'd been doing yesterday.

Thanks

**Comment by alanshaw** [comment]
@ackuser my slides from yesterday https://github.com/alanshaw/meteor-shiny included demos on maps and IM

**Comment by ackuser** [comment]
Thanks, I really appreciate it. I am having a look!
