### ISSUE TITLE
2015 Oct Hackathon

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#21]
On the weekend of October 10th and 11th, participants will come together for 24 hours to build Meteor apps, connect with Meteor developers from all over the world and, of course, compete for prizes.

[METEOR'S SIGN UP PAGE](http://info.meteor.com/2015-hackathon?utm_campaign=Core+Community&utm_source=hs_email&utm_medium=email&utm_content=21918935&_hsenc=p2ANqtz--EP5VUCLABqRvoFGFZwp75Y1oZjiHFqa7NiNyMdBOKGshe_G07t5ime_PoG6OF2Fcp_FKWAzQzzgyfcWrdMyfhrsaW1g&_hsmi=21918935)

**Comment by motapuma** [comment]
i wanna go? me i?
