### ISSUE TITLE
January 2016 - Meteor add react

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#23]
**THURSDAY 28th JANUARY**
- We have Judit Greskovits giving a feature talk on using react with Meteor
- We have Dr Matthew Yee-King of Coursera giving us an insiders look at their new Meteor course.
- Meteor News with Richard Silverton.
- NEW Meteor Surgery - Your questions answered ...
- Lightening Talks.

If you have a lightening talk (5min talk/demo)
or
If you have questions about Meteor you would like answered
please let us know by adding a :speech_balloon:  **Comment** below

**Comment by mrw34** [comment]
If you're short of lightening talks then I would be happy to explain how we're using CouchDB as a persistence layer for Meteor.

**Comment by bluxu** [comment]
I'm on the waiting list, but if you're still looking for lightning talks and the venue is sufficiently large then I'd be happy to come and talk about how we're using Meteor to build an academic collaboration and conference tool [http://www.collabor8research.org](http://www.collabor8research.org).

**Comment by kynan** [comment]
@bluxu That page looks effectively like a static page, why use meteor?

**Comment by bluxu** [comment]
@kynan - it's not a static page, it's a social networking and collaboration tool. Have you scrolled down to the "News" and "Profiles" sections?

**Comment by kynan** [comment]
OK, hadn't looked properly!
