### ISSUE TITLE
3rd March 2016

### ISSUE THREAD

**Issue by alanshaw** [meteor-london/next#24]
## Talks
- ~~[Babak Fakhamzadeh](https://github.com/MastaBaba) - City discovery with a twist~~
- [Bernat Orell](https://github.com/borellvi) - meteor + flux
- [Bruno Vinel](http://www.meetup.com/members/160043672/) - www.agily.io
## Lightning talks
- [Edward Hughes](https://github.com/bluxu) - Academic collaboration and conference (http://www.collabor8research.org/)

**Comment by MastaBaba** [comment]
Is there more clarity on the date of this meet up?

**Comment by olizilla** [comment]
:tada: 3rd March 2016

**Comment by MastaBaba** [comment]
Thanks, I saw the announcement on Gitter. I was set to speak, but, sadly, I won't be in London on the 3rd. :(

**Comment by reddog** [comment]
I have a particular implementation problem (minimising data and sharing between templates). Could I present in a lightning talk and seek out answers from the group?

**Comment by richsilv** [comment]
Yes, please do @reddog - that sounds interesting! Give everyone the background and a demo, and then let us know what you're struggling with.

**Comment by reddog** [comment]
Great - I'll add it to the list.  What's the duration for the lightning talks (including audience participation!)?

**Comment by richsilv** [comment]
5 minutes!

**Comment by reddog** [comment]
Hmmm... me, and the audience, are going to have to speak very quickly....!!! ;-)

**Comment by richsilv** [comment]
@reddog - what's the title of your talk, please?  You can use up most of the five minutes explaining the background, and if you don't have time for all the Q&A as a forum, I'm sure people will seek you out over a burrito or beer in the interval.

**Comment by reddog** [comment]
Do we have projector?

**Comment by richsilv** [comment]
Certainly!

**Comment by reddog** [comment]
Unfortunately I can't make tonight after all. Done in - managed to catch one of the many bugs doing the rounds!!  Next time?!

**Comment by richsilv** [comment]
No worries, thanks for letting us know.

**Comment by olizilla** [comment]
This was good, but now it's done.

Long live https://github.com/meteor-london/next/issues/25
