### ISSUE TITLE
April 2016 - TBC

### ISSUE THREAD

**Issue by olizilla** [meteor-london/next#25]
Shall we?

**Comment by xavxyz** [comment]
Hi @olizilla! 

I have been introduced to this issue by @maciej001: I'm a French meteor dev and I will be in London from April 21st to 26th afternoon.

I would be really glad to attend a Meteor London meetup and meet the community! :tada:

I'm kind of doing a `Meteor Meetup Tour` visiting friends in Netherlands and London, starting from Paris: there is Meteor Paris on April 19th and Meteor NL @ Amsterdam on April 20th.

I'll be giving a lightning talk at these meetups about making from scratch a webapp with Meteor 1.3 + React, following the recommended good practices by the guide, with highlights on what you can learn and hack during this process :smile:

So, I was wondering when do you think the next meetup will happen? Could I give a lightning talk?

**Comment by xavxyz** [comment]
@olizilla @richsilv http://www.meetup.com/fr-FR/Meteor-London/events/230374549/

Do you think it would be possible to do it on 25th for a sympathic French fellow here in London to meet the community as there are not a lot of people subscribed yet? 🙏  🙏
