### ISSUE TITLE
May 5th - Show and Tell

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#26]
Next Meetup - Thursday 5th May at Makers Academy
### Show and Tell

**Shakespeare in Shoreditch - Jimmy Tidey**
**Street Scenes - Matt Linares**

**Comment by jimmytidey** [comment]
Would love to do a show and tell of the  digital / physical map of Shoreditch, part of Shakespeare in Shoreditch festival. Project completed with @benj_kos and Oliver Smith. Lessons on using Meteor for installations. 

https://twitter.com/benj_kos/status/722839992708526080

**Comment by mattlinares** [comment]
I'd like to present a basic version of an event organiser app for [streetscenes.org.uk](http://streetscenes.org.uk), as well as the vision of the community project itself in the hope that some local Meteor folk might like to join me and contribute code for the good of their city.

Aside from just asking for help, I can pose interesting questions on the state of cooperative, public-life network platforms.

Presentation: http://matt.microsplash.org/streetscenesintro
