### ISSUE TITLE
September 2016 Meetup

### ISSUE THREAD

**Issue by bmordan** [meteor-london/next#28]
Thursday 29th September 2016 _6.30pm - 9pm_

Come and join us for London's Meteor night. Do you have a demo? a new app, a problem? Come and meet the developers who work with Meteor everyday. Leave this friendly and fun night inspired to have a go at making your idea come to life.

The event is sponsored by Meteor Development Group MDG (San Francisco) so you'll be treated to craft ales, burritos and a selection of soft drinks to enjoy as you socialise and meet the community.

We have two speakers lined up for the night 

Speakers:

Oli Evans - Meteor News
Richard Silverton - Data Aggregation Queries in Meteor
Bernard Mordan - Fast Mobile Development with Meteor

Lightening Talks (5mins)

Bring a talk - it's a buzz! The crowd are very positive and receptive - come and share your learnings walk away from the night feeling like a champion

**Comment by olizilla** [comment]
👍

**Comment by olizilla** [comment]
Maybe make a little more fuss over, IT'S ABOUT YOU! YOUR TALKS, DAMMIT. BRING A THING.

**Comment by ynotrusso** [comment]
I'll be presenting "Use Kanban" (https://usekanban.com) - A  productivity platform that integrates with Github, Gitlab, Bitbucket and Slack.

**Comment by olizilla** [comment]
👍
