### ISSUE TITLE
Meetup - 17th July 2014

### ISSUE THREAD

**Issue by olizilla** [meteor-london/next#3]
Speakers
@DominikGuzei - Prisma
@alanshaw - Server to Server DDP
@cwaring - Modern Art with Meteor
@cheeseen - The design of simple
@bmordan - Multi-touchy
@DominikGuzei - Space
@liamwooding - Surround Sounds

**Venue**: ustwo, 62 Shoreditch High St, London E1 6JJ

**Comment by cwaring** [comment]
I'll put myself down for our Tate hack. "Modern art with Meteor" or something suitably artsy.

**Comment by aychtang** [comment]
I plan on doing a recap on Deps, cover the ways Meteor provides a faster development workflow, explore Appcache + code reload implementation.

**Comment by cwaring** [comment]
I've just pinged ustwo to see if they can host us on the 17th, I'll update everyone when I hear back.

**Comment by cwaring** [comment]
ustwo confirmed for the 17th, I'll announce to the group today.

**Comment by olizilla** [comment]
@cheeseen hot.
@cwaring you are awesome. :heart_eyes_cat:

**Comment by bmordan** [comment]
Can I do a five minutes 'I built a thing, here is my thing' ? I'm really after one of alan's meteor speaker's badges. I'm total noob and have no real expertise. I'd talk about using hammer js - multi-touch events with meteor - and demo a few examples. https://github.com/bmordan/fingertracker - this is the first one. I'm working on some others.

What say ye?

Bernard

**Comment by aychtang** [comment]
I refactored my talk into a more high level concepty thing than a, "hello heres how to write the code cya later" thing. Basically going to be a series of observations on what it is  that makes Meteor an easy framework to build with.

@bmordan Totally! There are usually a lot of lightning talks, and I think yours would fit right in.

**Comment by olizilla** [comment]
Hey @DominikGuzei are you all good? We've got you down for a ~20min talk at the event this Thursday, so just shout if you have any questions. We usually try and keep the talks more demo focused, but do whatever works for you.

**Comment by DominikGuzei** [comment]
Hey @olizilla – yeah everything's fine, flight and accommodation are booked  :-)
Thanks for putting this event together, ~20 min. talk is great for me and I can also keep it more demo focused. I will just give a short overview of the architecture and how I used Meteor, what worked great and pitfalls I encountered.

**Comment by DominikGuzei** [comment]
Hey folks, if there is still time for a 5 min lightning talk I could also show a little bit of my open source micro-architecture "Space" for Meteor apps that I developed while working on Prisma. It helped me a lot in making my code more modular, configurable, and testable.

I had no time for real documentation yet, but you can read the package overview on atmosphere:
http://atmospherejs.com/package/space

**Comment by olizilla** [comment]
Awesome work team!
Thanks for all the talkings @cheeseen @jamesuren @DominikGuzei @alanshaw @liamwooding 
@bmordan 
Thanks to @cwaring for gallantly offering to move his talk to next month so others could talk this month.
ONWARDS: https://github.com/meteor-london/next/issues/6

**Comment by olizilla** [comment]
Videos are up:
https://www.youtube.com/playlist?list=PLTUf4ytkmI8T-0GcwGph76wlnbbOLcYKt
