### ISSUE TITLE
LDN hackathon to mirror the SF hackathon?

### ISSUE THREAD

**Issue by cwaring** [meteor-london/next#4]
The 2nd annual Meteor hackathon is scheduled for July 26-27. How about we organise a partner event to run alongside this one?

http://hackathon.meteor.com/

**Comment by alanshaw** [comment]
Monumental bad timing! That's international nodebots day(s)!

**Comment by olizilla** [comment]
A good idea though, @cwaring would you be up for running it? @achingbrain and @alanshaw are otherwise disposed on nodebots and I'm away on holiday that week.

Anyone else is interested in a weekend Meteor hack? We could pin it as a suggested event on meetup and see.

**Comment by cwaring** [comment]
I'd be up for that if we get a couple of helpers signed up. Or perhaps pair the events if we can get a big enough space.

**Comment by cwaring** [comment]
So chaps, are you running the Nodebots hackathon over both of these days or just the Sunday? If so it might be possible to piggyback one into the other. I have @angiemaguire on the team too!

**Comment by achingbrain** [comment]
NodeBots is just on the Sunday. @olizilla is out of town and @alanshaw and I are busy on the Saturday.

**Comment by olizilla** [comment]
So I guess we are still down a Meteor hack day. Any interest in organising one? I think people want it.

**Comment by josephfinlayson** [comment]
I want it.
