### ISSUE TITLE
Meetup - 14th August 2014

### ISSUE THREAD

**Issue by olizilla** [meteor-london/next#6]
~~Date & venue still TBC, but there _will_ be a Devshop London in August!~~
14th August 2014, at the [ustwo](http://ustwo.com) office: [62 Shoreditch High Street](https://maps.google.com/maps?q=62+Shoreditch+High+Street+London+E1+6JJ+United+Kingdom&hl=en&sll=40.747244,-73.995747&sspn=0.014972,0.023432&gl=us&hnear=62+Shoreditch+High+St,+London,+United+Kingdom&t=m&z=16)

**Comment by olizilla** [comment]
Speakers:
~~@raedle - huddle - multi device magic with meteor~~ Can't make it, we'll try again in Sept.
@cwaring Modern art with Meteor
@zakir2k GoEatWith
@richsilv Publications
~~@jongd TBC~~
@ficshelf FicShelf writing/publishing platform
~~@liamwooding surround cows MKII~~
@kimon-satan Orfeo
@olizilla @alanshaw @cwaring: DRIIFT - real-time adventures in near-field

**Comment by zakir2k** [comment]
@olizilla  Please add me as a speaker @zakir2k - GoEatWith - come dine with me style eventing.
Thanks.
Zak

**Comment by olizilla** [comment]
@cwaring can you see if ustwo will host meteor-london again? Is everyone free on August 14th?

**Comment by alanshaw** [comment]
I'm free

**Comment by olizilla** [comment]
@zakir2k great. I'll put you down for a lightening talk. The projector uses HDMI, and we have adapters for DVI and mini-displayport. Does your laptop support one of them, or can you use the house laptop?

**Comment by zakir2k** [comment]
Macbook Air. all good.

**Comment by olizilla** [comment]
@raedle are you available on the 14th of August? Likewise @zakir2k, @cwaring @alanshaw @jongd @cheeseen?
We just got the ok from ustwo that we can use their venue again.

**Comment by zakir2k** [comment]
Available.

**Comment by alanshaw** [comment]
:thumbsup:

**Comment by jem-computer** [comment]
:thumbsup: :thumbsup:

**Comment by cwaring** [comment]
:+1: :neckbeard:

**Comment by richsilv** [comment]
I'm working on something I'd like to show off, which already provides a great example of using Meteor's low-level publications API (with which I've recently become obsessed) and I'm _hoping_ to get working with Famo.us by next week.  I'll post a link as soon as I've got something vaguely stable.

Ironically, having said all that I don't even know how to do a thumbs up emoticon to express my enthusiasm.

**Comment by aychtang** [comment]
:-1: I have to go to a friends gig that evening.

**Comment by jcharvet** [comment]
:thumbsup:

**Comment by ficshelf** [comment]
FicShelf  is launching this week an early Beta of our MeteorJS based marketplace for writers, editors and designers. Would love to share our experiences.

**Comment by olizilla** [comment]
@kimon-satan are you up for a lightening talk this month?

**Comment by kimon-satan** [comment]
Yep that suits me fine.

**Comment by olizilla** [comment]
Reminder to everyone who wants to use the projector

> The projector uses HDMI, and we have adapters for DVI and mini-displayport. Does your laptop support one of them, or can you use the house laptop?

**Comment by richsilv** [comment]
HDMI works for me.  I've even got a presentation this time:

https://www.haikudeck.com/p/IqX3PYjPGs/candlestick-charting

**Comment by ficshelf** [comment]
HDMI please

**Comment by kimon-satan** [comment]
I'm mini-display but can use house laptop if necessary

**Comment by zakir2k** [comment]
mini display is cool for me too

**Comment by zakir2k** [comment]
any chance we can get a copy or link to the video for the event last night? would be good to see for future improvements. Cheers. Zak

**Comment by ficshelf** [comment]
I would love it too!

**Comment by olizilla** [comment]
Of course! They'll be ready next week.

**Comment by olizilla** [comment]
Thanks @richsilv @zakir2k @ficshelf @Tarang @kimon-satan @cwaring for the great talks!

**Comment by cwaring** [comment]
Thanks everyone. I really enjoyed the night. Great to hear all your stories!

**Comment by olizilla** [comment]
Videos are up! 
https://www.youtube.com/playlist?list=PLTUf4ytkmI8TtB8XshfLIiVu-Re9SNDxW
